_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 51
                - 55
            "2":
                - 1
                - 51
                - 55
            "3":
                - 2
                - 18
                - 23
                - 55
            "4": 3.10.18
            "5": 0.18.2
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
resolved__vae__2d_ellipse__cfg__batch_size:
    value: 128
resolved__vae__2d_ellipse__cfg__beta_final:
    value: 0.05
resolved__vae__2d_ellipse__cfg__device:
    value: cuda
resolved__vae__2d_ellipse__cfg__epochs:
    value: 500
resolved__vae__2d_ellipse__cfg__hidden_dims:
    value:
        - 128
        - 128
        - 128
resolved__vae__2d_ellipse__cfg__latent_dim:
    value: -1
resolved__vae__2d_ellipse__cfg__lr:
    value: 0.001
resolved__vae__2d_ellipse__cfg__n_grid:
    value: 4096
resolved__vae__2d_ellipse__cfg__n_train:
    value: 128
resolved__vae__2d_ellipse__cfg__planner__anim_fps:
    value: 6
resolved__vae__2d_ellipse__cfg__planner__anim_stride:
    value: 1
resolved__vae__2d_ellipse__cfg__planner__init_mode:
    value: joint_spline
resolved__vae__2d_ellipse__cfg__planner__joint_mid_noise:
    value: 0
resolved__vae__2d_ellipse__cfg__planner__lam_len_joint:
    value: 0.4
resolved__vae__2d_ellipse__cfg__planner__lam_manifold:
    value: 1
resolved__vae__2d_ellipse__cfg__planner__method:
    value: trajectory_opt
resolved__vae__2d_ellipse__cfg__planner__opt_lam_smooth:
    value: 0.2
resolved__vae__2d_ellipse__cfg__planner__opt_lr:
    value: 0.01
resolved__vae__2d_ellipse__cfg__planner__opt_steps:
    value: 1240
resolved__vae__2d_ellipse__cfg__planner__pair_max_ratio:
    value: 0.35
resolved__vae__2d_ellipse__cfg__planner__pair_min_ratio:
    value: 0.15
resolved__vae__2d_ellipse__cfg__planner__pair_tries:
    value: 1200
resolved__vae__2d_ellipse__cfg__planner__pybullet_real_time_dt:
    value: 0.06
resolved__vae__2d_ellipse__cfg__planner__pybullet_render:
    value: false
resolved__vae__2d_ellipse__cfg__planner__save_gif:
    value: false
resolved__vae__2d_ellipse__cfg__planner__trust_scale:
    value: 0.8
resolved__vae__2d_ellipse__cfg__projector__alpha:
    value: 0.3
resolved__vae__2d_ellipse__cfg__projector__min_steps:
    value: 20
resolved__vae__2d_ellipse__cfg__projector__steps:
    value: 80
resolved__vae__2d_ellipse__cfg__seed:
    value: 173
resolved__vae__2d_ellipse__cfg__ur5_backend:
    value: auto
resolved__vae__2d_ellipse__cfg__viz_enable:
    value: true
resolved__vae__2d_ellipse__cfg__viz_max_eval_points:
    value: 2000
resolved__vae__2d_ellipse__cfg__viz_sample_latent_n:
    value: 150
resolved__vae__2d_ellipse__cfg__warmup_epochs:
    value: 440
resolved__vae__2d_ellipse__cfg__weight_decay:
    value: 0
resolved__vae__2d_ellipse__loaded_config_paths:
    value:
        - /home/baiyu/PycharmProjects/equality_manofld/configs/base.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/methods/vae.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/datasets/2d_ellipse.json
resolved__vae__2d_ellipse__loaded_layers_count:
    value: 3
resolved__vae__2d_ellipse__seed:
    value: 173
resolved__vae__2d_figure_eight__cfg__batch_size:
    value: 128
resolved__vae__2d_figure_eight__cfg__beta_final:
    value: 0.05
resolved__vae__2d_figure_eight__cfg__device:
    value: cuda
resolved__vae__2d_figure_eight__cfg__epochs:
    value: 500
resolved__vae__2d_figure_eight__cfg__hidden_dims:
    value:
        - 128
        - 128
        - 128
resolved__vae__2d_figure_eight__cfg__latent_dim:
    value: -1
resolved__vae__2d_figure_eight__cfg__lr:
    value: 0.001
resolved__vae__2d_figure_eight__cfg__n_grid:
    value: 4096
resolved__vae__2d_figure_eight__cfg__n_train:
    value: 128
resolved__vae__2d_figure_eight__cfg__planner__anim_fps:
    value: 6
resolved__vae__2d_figure_eight__cfg__planner__anim_stride:
    value: 1
resolved__vae__2d_figure_eight__cfg__planner__init_mode:
    value: joint_spline
resolved__vae__2d_figure_eight__cfg__planner__joint_mid_noise:
    value: 0
resolved__vae__2d_figure_eight__cfg__planner__lam_len_joint:
    value: 0.4
resolved__vae__2d_figure_eight__cfg__planner__lam_manifold:
    value: 1
resolved__vae__2d_figure_eight__cfg__planner__method:
    value: trajectory_opt
resolved__vae__2d_figure_eight__cfg__planner__opt_lam_smooth:
    value: 0.2
resolved__vae__2d_figure_eight__cfg__planner__opt_lr:
    value: 0.01
resolved__vae__2d_figure_eight__cfg__planner__opt_steps:
    value: 1240
resolved__vae__2d_figure_eight__cfg__planner__pair_max_ratio:
    value: 0.35
resolved__vae__2d_figure_eight__cfg__planner__pair_min_ratio:
    value: 0.15
resolved__vae__2d_figure_eight__cfg__planner__pair_tries:
    value: 1200
resolved__vae__2d_figure_eight__cfg__planner__pybullet_real_time_dt:
    value: 0.06
resolved__vae__2d_figure_eight__cfg__planner__pybullet_render:
    value: false
resolved__vae__2d_figure_eight__cfg__planner__save_gif:
    value: false
resolved__vae__2d_figure_eight__cfg__planner__trust_scale:
    value: 0.8
resolved__vae__2d_figure_eight__cfg__projector__alpha:
    value: 0.3
resolved__vae__2d_figure_eight__cfg__projector__min_steps:
    value: 20
resolved__vae__2d_figure_eight__cfg__projector__steps:
    value: 80
resolved__vae__2d_figure_eight__cfg__seed:
    value: 173
resolved__vae__2d_figure_eight__cfg__ur5_backend:
    value: auto
resolved__vae__2d_figure_eight__cfg__viz_enable:
    value: true
resolved__vae__2d_figure_eight__cfg__viz_max_eval_points:
    value: 2000
resolved__vae__2d_figure_eight__cfg__viz_sample_latent_n:
    value: 150
resolved__vae__2d_figure_eight__cfg__warmup_epochs:
    value: 440
resolved__vae__2d_figure_eight__cfg__weight_decay:
    value: 0
resolved__vae__2d_figure_eight__loaded_config_paths:
    value:
        - /home/baiyu/PycharmProjects/equality_manofld/configs/base.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/methods/vae.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/datasets/2d_figure_eight.json
resolved__vae__2d_figure_eight__loaded_layers_count:
    value: 3
resolved__vae__2d_figure_eight__seed:
    value: 173
resolved__vae__2d_looped_spiro__cfg__batch_size:
    value: 128
resolved__vae__2d_looped_spiro__cfg__beta_final:
    value: 0.05
resolved__vae__2d_looped_spiro__cfg__device:
    value: cuda
resolved__vae__2d_looped_spiro__cfg__epochs:
    value: 500
resolved__vae__2d_looped_spiro__cfg__hidden_dims:
    value:
        - 128
        - 128
        - 128
resolved__vae__2d_looped_spiro__cfg__latent_dim:
    value: -1
resolved__vae__2d_looped_spiro__cfg__lr:
    value: 0.001
resolved__vae__2d_looped_spiro__cfg__n_grid:
    value: 4096
resolved__vae__2d_looped_spiro__cfg__n_train:
    value: 128
resolved__vae__2d_looped_spiro__cfg__planner__anim_fps:
    value: 6
resolved__vae__2d_looped_spiro__cfg__planner__anim_stride:
    value: 1
resolved__vae__2d_looped_spiro__cfg__planner__init_mode:
    value: joint_spline
resolved__vae__2d_looped_spiro__cfg__planner__joint_mid_noise:
    value: 0
resolved__vae__2d_looped_spiro__cfg__planner__lam_len_joint:
    value: 0.4
resolved__vae__2d_looped_spiro__cfg__planner__lam_manifold:
    value: 1
resolved__vae__2d_looped_spiro__cfg__planner__method:
    value: trajectory_opt
resolved__vae__2d_looped_spiro__cfg__planner__opt_lam_smooth:
    value: 0.2
resolved__vae__2d_looped_spiro__cfg__planner__opt_lr:
    value: 0.01
resolved__vae__2d_looped_spiro__cfg__planner__opt_steps:
    value: 1240
resolved__vae__2d_looped_spiro__cfg__planner__pair_max_ratio:
    value: 0.35
resolved__vae__2d_looped_spiro__cfg__planner__pair_min_ratio:
    value: 0.15
resolved__vae__2d_looped_spiro__cfg__planner__pair_tries:
    value: 1200
resolved__vae__2d_looped_spiro__cfg__planner__pybullet_real_time_dt:
    value: 0.06
resolved__vae__2d_looped_spiro__cfg__planner__pybullet_render:
    value: false
resolved__vae__2d_looped_spiro__cfg__planner__save_gif:
    value: false
resolved__vae__2d_looped_spiro__cfg__planner__trust_scale:
    value: 0.8
resolved__vae__2d_looped_spiro__cfg__projector__alpha:
    value: 0.3
resolved__vae__2d_looped_spiro__cfg__projector__min_steps:
    value: 20
resolved__vae__2d_looped_spiro__cfg__projector__steps:
    value: 80
resolved__vae__2d_looped_spiro__cfg__seed:
    value: 173
resolved__vae__2d_looped_spiro__cfg__ur5_backend:
    value: auto
resolved__vae__2d_looped_spiro__cfg__viz_enable:
    value: true
resolved__vae__2d_looped_spiro__cfg__viz_max_eval_points:
    value: 2000
resolved__vae__2d_looped_spiro__cfg__viz_sample_latent_n:
    value: 150
resolved__vae__2d_looped_spiro__cfg__warmup_epochs:
    value: 440
resolved__vae__2d_looped_spiro__cfg__weight_decay:
    value: 0
resolved__vae__2d_looped_spiro__loaded_config_paths:
    value:
        - /home/baiyu/PycharmProjects/equality_manofld/configs/base.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/methods/vae.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/datasets/2d_looped_spiro.json
resolved__vae__2d_looped_spiro__loaded_layers_count:
    value: 3
resolved__vae__2d_looped_spiro__seed:
    value: 173
resolved__vae__2d_planar_arm_line_n2__cfg__batch_size:
    value: 128
resolved__vae__2d_planar_arm_line_n2__cfg__beta_final:
    value: 0.05
resolved__vae__2d_planar_arm_line_n2__cfg__device:
    value: cuda
resolved__vae__2d_planar_arm_line_n2__cfg__epochs:
    value: 500
resolved__vae__2d_planar_arm_line_n2__cfg__hidden_dims:
    value:
        - 128
        - 128
        - 128
resolved__vae__2d_planar_arm_line_n2__cfg__latent_dim:
    value: -1
resolved__vae__2d_planar_arm_line_n2__cfg__lr:
    value: 0.001
resolved__vae__2d_planar_arm_line_n2__cfg__n_grid:
    value: 4096
resolved__vae__2d_planar_arm_line_n2__cfg__n_train:
    value: 128
resolved__vae__2d_planar_arm_line_n2__cfg__planner__anim_fps:
    value: 6
resolved__vae__2d_planar_arm_line_n2__cfg__planner__anim_stride:
    value: 1
resolved__vae__2d_planar_arm_line_n2__cfg__planner__init_mode:
    value: joint_spline
resolved__vae__2d_planar_arm_line_n2__cfg__planner__joint_mid_noise:
    value: 0
resolved__vae__2d_planar_arm_line_n2__cfg__planner__lam_len_joint:
    value: 0.4
resolved__vae__2d_planar_arm_line_n2__cfg__planner__lam_manifold:
    value: 1
resolved__vae__2d_planar_arm_line_n2__cfg__planner__method:
    value: trajectory_opt
resolved__vae__2d_planar_arm_line_n2__cfg__planner__opt_lam_smooth:
    value: 0.2
resolved__vae__2d_planar_arm_line_n2__cfg__planner__opt_lr:
    value: 0.01
resolved__vae__2d_planar_arm_line_n2__cfg__planner__opt_steps:
    value: 1240
resolved__vae__2d_planar_arm_line_n2__cfg__planner__pair_max_ratio:
    value: 0.35
resolved__vae__2d_planar_arm_line_n2__cfg__planner__pair_min_ratio:
    value: 0.15
resolved__vae__2d_planar_arm_line_n2__cfg__planner__pair_tries:
    value: 1200
resolved__vae__2d_planar_arm_line_n2__cfg__planner__pybullet_real_time_dt:
    value: 0.06
resolved__vae__2d_planar_arm_line_n2__cfg__planner__pybullet_render:
    value: false
resolved__vae__2d_planar_arm_line_n2__cfg__planner__save_gif:
    value: false
resolved__vae__2d_planar_arm_line_n2__cfg__planner__trust_scale:
    value: 0.8
resolved__vae__2d_planar_arm_line_n2__cfg__projector__alpha:
    value: 0.3
resolved__vae__2d_planar_arm_line_n2__cfg__projector__min_steps:
    value: 20
resolved__vae__2d_planar_arm_line_n2__cfg__projector__steps:
    value: 80
resolved__vae__2d_planar_arm_line_n2__cfg__seed:
    value: 173
resolved__vae__2d_planar_arm_line_n2__cfg__ur5_backend:
    value: auto
resolved__vae__2d_planar_arm_line_n2__cfg__viz_enable:
    value: true
resolved__vae__2d_planar_arm_line_n2__cfg__viz_max_eval_points:
    value: 2000
resolved__vae__2d_planar_arm_line_n2__cfg__viz_sample_latent_n:
    value: 150
resolved__vae__2d_planar_arm_line_n2__cfg__warmup_epochs:
    value: 440
resolved__vae__2d_planar_arm_line_n2__cfg__weight_decay:
    value: 0
resolved__vae__2d_planar_arm_line_n2__loaded_config_paths:
    value:
        - /home/baiyu/PycharmProjects/equality_manofld/configs/base.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/methods/vae.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/datasets/2d_planar_arm_line_n2.json
resolved__vae__2d_planar_arm_line_n2__loaded_layers_count:
    value: 3
resolved__vae__2d_planar_arm_line_n2__seed:
    value: 173
resolved__vae__2d_sparse_sine__cfg__batch_size:
    value: 128
resolved__vae__2d_sparse_sine__cfg__beta_final:
    value: 0.05
resolved__vae__2d_sparse_sine__cfg__device:
    value: cuda
resolved__vae__2d_sparse_sine__cfg__epochs:
    value: 500
resolved__vae__2d_sparse_sine__cfg__hidden_dims:
    value:
        - 128
        - 128
        - 128
resolved__vae__2d_sparse_sine__cfg__latent_dim:
    value: -1
resolved__vae__2d_sparse_sine__cfg__lr:
    value: 0.001
resolved__vae__2d_sparse_sine__cfg__n_grid:
    value: 4096
resolved__vae__2d_sparse_sine__cfg__n_train:
    value: 128
resolved__vae__2d_sparse_sine__cfg__planner__anim_fps:
    value: 6
resolved__vae__2d_sparse_sine__cfg__planner__anim_stride:
    value: 1
resolved__vae__2d_sparse_sine__cfg__planner__init_mode:
    value: joint_spline
resolved__vae__2d_sparse_sine__cfg__planner__joint_mid_noise:
    value: 0
resolved__vae__2d_sparse_sine__cfg__planner__lam_len_joint:
    value: 0.4
resolved__vae__2d_sparse_sine__cfg__planner__lam_manifold:
    value: 1
resolved__vae__2d_sparse_sine__cfg__planner__method:
    value: trajectory_opt
resolved__vae__2d_sparse_sine__cfg__planner__opt_lam_smooth:
    value: 0.2
resolved__vae__2d_sparse_sine__cfg__planner__opt_lr:
    value: 0.01
resolved__vae__2d_sparse_sine__cfg__planner__opt_steps:
    value: 1240
resolved__vae__2d_sparse_sine__cfg__planner__pair_max_ratio:
    value: 0.35
resolved__vae__2d_sparse_sine__cfg__planner__pair_min_ratio:
    value: 0.15
resolved__vae__2d_sparse_sine__cfg__planner__pair_tries:
    value: 1200
resolved__vae__2d_sparse_sine__cfg__planner__pybullet_real_time_dt:
    value: 0.06
resolved__vae__2d_sparse_sine__cfg__planner__pybullet_render:
    value: false
resolved__vae__2d_sparse_sine__cfg__planner__save_gif:
    value: false
resolved__vae__2d_sparse_sine__cfg__planner__trust_scale:
    value: 0.8
resolved__vae__2d_sparse_sine__cfg__projector__alpha:
    value: 0.3
resolved__vae__2d_sparse_sine__cfg__projector__min_steps:
    value: 20
resolved__vae__2d_sparse_sine__cfg__projector__steps:
    value: 80
resolved__vae__2d_sparse_sine__cfg__seed:
    value: 173
resolved__vae__2d_sparse_sine__cfg__ur5_backend:
    value: auto
resolved__vae__2d_sparse_sine__cfg__viz_enable:
    value: true
resolved__vae__2d_sparse_sine__cfg__viz_max_eval_points:
    value: 2000
resolved__vae__2d_sparse_sine__cfg__viz_sample_latent_n:
    value: 150
resolved__vae__2d_sparse_sine__cfg__warmup_epochs:
    value: 440
resolved__vae__2d_sparse_sine__cfg__weight_decay:
    value: 0
resolved__vae__2d_sparse_sine__loaded_config_paths:
    value:
        - /home/baiyu/PycharmProjects/equality_manofld/configs/base.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/methods/vae.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/datasets/2d_sparse_sine.json
resolved__vae__2d_sparse_sine__loaded_layers_count:
    value: 3
resolved__vae__2d_sparse_sine__seed:
    value: 173
resolved__vae__2d_square__cfg__batch_size:
    value: 128
resolved__vae__2d_square__cfg__beta_final:
    value: 0.05
resolved__vae__2d_square__cfg__device:
    value: cuda
resolved__vae__2d_square__cfg__epochs:
    value: 500
resolved__vae__2d_square__cfg__hidden_dims:
    value:
        - 128
        - 128
        - 128
resolved__vae__2d_square__cfg__latent_dim:
    value: -1
resolved__vae__2d_square__cfg__lr:
    value: 0.001
resolved__vae__2d_square__cfg__n_grid:
    value: 4096
resolved__vae__2d_square__cfg__n_train:
    value: 128
resolved__vae__2d_square__cfg__planner__anim_fps:
    value: 6
resolved__vae__2d_square__cfg__planner__anim_stride:
    value: 1
resolved__vae__2d_square__cfg__planner__init_mode:
    value: joint_spline
resolved__vae__2d_square__cfg__planner__joint_mid_noise:
    value: 0
resolved__vae__2d_square__cfg__planner__lam_len_joint:
    value: 0.4
resolved__vae__2d_square__cfg__planner__lam_manifold:
    value: 1
resolved__vae__2d_square__cfg__planner__method:
    value: trajectory_opt
resolved__vae__2d_square__cfg__planner__opt_lam_smooth:
    value: 0.2
resolved__vae__2d_square__cfg__planner__opt_lr:
    value: 0.01
resolved__vae__2d_square__cfg__planner__opt_steps:
    value: 1240
resolved__vae__2d_square__cfg__planner__pair_max_ratio:
    value: 0.35
resolved__vae__2d_square__cfg__planner__pair_min_ratio:
    value: 0.15
resolved__vae__2d_square__cfg__planner__pair_tries:
    value: 1200
resolved__vae__2d_square__cfg__planner__pybullet_real_time_dt:
    value: 0.06
resolved__vae__2d_square__cfg__planner__pybullet_render:
    value: false
resolved__vae__2d_square__cfg__planner__save_gif:
    value: false
resolved__vae__2d_square__cfg__planner__trust_scale:
    value: 0.8
resolved__vae__2d_square__cfg__projector__alpha:
    value: 0.3
resolved__vae__2d_square__cfg__projector__min_steps:
    value: 20
resolved__vae__2d_square__cfg__projector__steps:
    value: 80
resolved__vae__2d_square__cfg__seed:
    value: 173
resolved__vae__2d_square__cfg__ur5_backend:
    value: auto
resolved__vae__2d_square__cfg__viz_enable:
    value: true
resolved__vae__2d_square__cfg__viz_max_eval_points:
    value: 2000
resolved__vae__2d_square__cfg__viz_sample_latent_n:
    value: 150
resolved__vae__2d_square__cfg__warmup_epochs:
    value: 440
resolved__vae__2d_square__cfg__weight_decay:
    value: 0
resolved__vae__2d_square__loaded_config_paths:
    value:
        - /home/baiyu/PycharmProjects/equality_manofld/configs/base.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/methods/vae.json
        - /home/baiyu/PycharmProjects/equality_manofld/configs/datasets/2d_square.json
resolved__vae__2d_square__loaded_layers_count:
    value: 3
resolved__vae__2d_square__seed:
    value: 173
seed:
    value: 173
